kind: pipeline
name: default

steps:
  - name: build
    image: maven:3-eclipse-temurin-17
    commands:
      - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
      - mvn test -B
    when:
      branch:
        - main