settings:
  uhcworlds: ['world', 'world_nether']
  lobbyworlds: ['flat']
  teams: 4
  friendly-fire: false
  border:
    center-x: 0
    center-z: 0
    size: 4000
spawn:
  world: __UNSET__
  x: 0.0
  y: 0.0
  z: 0.0
  yaw: 0.0
  pitch: 0.0
firework-pos:
  1:
    world: __UNSET__
    x: 0.0
    y: 0.0
    z: 0.0
teams:
  - '§9Blue'
  - '§cRed'
  - '§aGreen'
  - '§eYellow'
  - '§5Purple'
  - '§6Orange'
  - '§8Black'
  - '§dPink'
team-items:
  - 'BLUE_WOOL'
  - 'RED_WOOL'
  - 'LIME_WOOL'
  - 'YELLOW_WOOL'
  - 'PURPLE_WOOL'
  - 'ORANGE_WOOL'
  - 'BLACK_WOOL'
  - 'PINK_WOOL'